export interface ButtonMapping {
  id: string;
  pin: number;
  key: string; // The keyboard key or function name
  description: string;
}

export interface CoinConfig {
  pin: number;
  pulsesPerCredit: number;
  creditValue: number; // Value in currency or credits per pulse train
  bounceTime: number; // Debounce time in ms
}

export interface AppConfig {
  useKeyboardLib: boolean; // True for Leonardo/Micro, False for Serial/Uno
  baudRate: number;
  buttons: ButtonMapping[];
  coin: CoinConfig;
  customLogic: string; // Logic generated by Gemini
}

export enum GeminiStatus {
  IDLE = 'IDLE',
  LOADING = 'LOADING',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}